### ISSUE TITLE
2012/13 season, Manchester united is not correctly handled.

### ISSUE THREAD

**Issue by vkdltjs** [openfootball/england#32]
When I did ```sportdb build``` and looked up the exported sport.db sqlite file, I found that Manchester United's match number is only 19 in 2012/13 season.

https://github.com/openfootball/england/blob/master/2012-13/1-premierleague-ii.txt
This file describes Manchester united as "Manchester U" and Manchester City as "Manchester C", and
https://github.com/openfootball/england/blob/master/.build/conf.txt
```
[10/81] >2012-13/1-premierleague-ii.txt<
  1 section(s):
    261 lines - league: >English Premier League< (eng.1), season: >2012/13<
      20 clubs:
        Arsenal x19 => Arsenal FC
        Aston Villa x19 => Aston Villa FC
        Chelsea x19 => Chelsea FC
        Everton x19 => Everton FC
        Fulham x19 => Fulham FC
        Liverpool x19 => Liverpool FC
        Manchester C x19 => Manchester City FC
        Manchester U x19 => Manchester United FC
```
I think the last two line don't handle the conversion correctly.
I don't know why.
But you can confirm something is wrong by doing what I did:

> When I did ```sportdb build``` and looked up the exported sport.db sqlite file, I found that Manchester United's match number is only 19 in 2012/13 season.

**Comment by geraldb** [comment]
Thanks for reporting. I can't answer without running the code to see what's wrong. What I can say is that all "allowed" or known name variants are listed in <https://github.com/openfootball/clubs/blob/master/europe/england/eng.clubs.txt#L78>  If you check Manchester United it has the entry Manchester U.   - not sure if the dot (.) in U. makes the trouble in the new matcher - sorry for the trouble I try to fix it in the next days - thanks for the patience (I assume it's a bug in the match parser / club matcher not removing the `.` before lookup). Cheers.

**Comment by geraldb** [comment]
FYI: The bug (matching club names using "normalized" names) is now fixed in the lastest match reader update.  Again thanks for reporting. Keep it up. Cheers.
